import Head from 'next/head'

import Navbar from './components/navbar';
import About from "./components/about";

export default function AboutPage() {
  return (
    <div>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <About />
      
    </div>
  )
}
